#ifndef MINESWEEPERSOLVER_ERROR_CODES_H
#define MINESWEEPERSOLVER_ERROR_CODES_H

typedef enum {
    RETURN_CODE_SUCCESS,
    ERROR_INCORRECT_USAGE_ARG_NUMBER,
    ERROR_INCORRECT_USAGE_ILLEGAL_LEVEL,
    ERROR_RAISE_MINESWEEPER_CREATE_PROCESS_FAILED,
    ERROR_MOVE_CURSOR_OUT_OF_BOARD_FIND_WINDOW_FAILED,
    ERROR_INITIALIZE_BOARD_MEMORY,
    ERROR_MOVE_CURSOR_OUT_OF_BOARD_CLIENT_TO_SCREEN_FAILED,
    ERROR_MOVE_CURSOR_OUT_OF_BOARD_SET_CURSOR_POS_FAILED,
    ERROR_CLICK_FIND_WINDOW_FAILED,
    ERROR_CLICK_SET_CURSOR_POS,
    ERROR_TRANSLATE_MINESWEEPER_POINT_TO_SCREEN_FIND_WINDOW_FAILED,
    ERROR_TRANSLATE_MINESWEEPER_POINT_TO_SCREEN_CLIENT_TO_SCREEN_FAILED,
    ERROR_GET_MOVE_ILLEGAL_BOARD_DETECTED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_FIND_WINDOW_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_GET_WINDOW_RECT_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_GET_DC_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_CREATE_COMPATIBLE_DC_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_CREATE_COMPATIBLE_BITMAP_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_SELECT_OBJECT_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_BIT_BLT_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_DELETE_DC_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_MEMORY_ALLOC_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_GET_DIBITS_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_DELETE_OBJECT_FAILED,
    ERROR_GET_MINESWEEPER_SCREENSHOT_RELEASEDC_FAILED,
    ERROR_CREATING_LOG_FILE_NAME,
    ERROR_OPENING_LOG_FILE,
    ERROR_CLOSING_LOG_FILE,
    ERROR_CREATING_LOGS_DIRECTORY,
    ERROR_WRITE_LOG_FFLUSH_FAILED,
    ERROR_WRITE_LOG_FPRINTF_FAILED,
    ERROR_INITIALIZE_MATRIX_MEMORY_ALLOC
} t_error_code;

#endif //MINESWEEPERSOLVER_ERROR_CODES_H
