#ifndef MINESWEEPERSOLVER_HARD_CODED_CONFIG_H
#define MINESWEEPERSOLVER_HARD_CODED_CONFIG_H

#define MINESWEEPER_PATH "..\\minesweeper\\Minesweeper X.exe"
#define MINESWEEPER_WINDOW_NAME "Minesweeper X"
#define DEBUG_LOGGING false
#define RUNTIME_LOGGING true

#endif //MINESWEEPERSOLVER_HARD_CODED_CONFIG_H
